<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MatakuliahSeeder extends Seeder
{
    public function run()
    {
        $matkul = [
            // PNF
            ['kode' => 'PNF-103', 'nama matakuliah' => 'Komunikasi Sosial'],
            ['kode' => 'PNF-201', 'nama matakuliah' => 'Kepemimpinan PNF'],
            ['kode' => 'PNF-301', 'nama matakuliah' => 'Pendidikan Orang Dewasa'],
            ['kode' => 'MKU-102', 'nama matakuliah' => 'Pancasila'],
            ['kode' => 'PNF-304', 'nama matakuliah' => 'Analisis Kebijakan PNF'],
            ['kode' => 'PNF-206', 'nama matakuliah' => 'Pengembangan Kurikulum PNF'],
            ['kode' => 'MFA-106', 'nama matakuliah' => 'Perkembangan Peserta Didik'],
            ['kode' => 'PNF-207', 'nama matakuliah' => 'Bimbingan Menulis Karya Ilmiah'],
            ['kode' => 'PNF-209', 'nama matakuliah' => 'Pengembangan Program Literasi'],
            ['kode' => 'PNF-205', 'nama matakuliah' => 'Difusi Inovasi Pendidikan'],
            ['kode' => 'PNF-208', 'nama matakuliah' => 'Identifikasi Kebutuhan dan Sumber Belajar Masyarakat'],
            ['kode' => 'MFA-104', 'nama matakuliah' => 'Kurikulum dan Pembelajaran'],
            ['kode' => 'PNF-101', 'nama matakuliah' => 'Konsep Dasar Pendidikan Nonformal'],
            ['kode' => 'PNF-102', 'nama matakuliah' => 'Pendidikan Sepanjang Hayat'],
            ['kode' => 'PNF-303', 'nama matakuliah' => 'Pendidikan Keluarga'],
            ['kode' => 'PNF-4148', 'nama matakuliah' => 'Seminar Proposal Skripsi'],
            ['kode' => 'PNF-208', 'nama matakuliah' => 'Profesi Pendidik dan Tenaga Kependidikan PNF'],
            ['kode' => 'PNF-305', 'nama matakuliah' => 'Homeschooling'],
            ['kode' => 'PNF-306', 'nama matakuliah' => 'Evaluasi Program PNF'],
            ['kode' => 'MKU-105', 'nama matakuliah' => 'Bahasa Inggris'],
            ['kode' => 'PNF-202', 'nama matakuliah' => 'Karya Kreatif Mahasiswa'],
            ['kode' => 'PNF-308', 'nama matakuliah' => 'Penelitian Tindakan dalam Pembelajaran PNF'],
            ['kode' => 'MFA-101', 'nama matakuliah' => 'Filsafat Pendidikan'],
            ['kode' => 'PNF-204', 'nama matakuliah' => 'Teknologi Pembelajaran PNF'],
            ['kode' => 'PNF-203', 'nama matakuliah' => 'Pendidikan Kepemudaan'],
            ['kode' => 'PNF-307', 'nama matakuliah' => 'Manajemen Diklat'],

            // Kimia
            ['kode' => 'KIM-205', 'nama matakuliah' => 'Kesetimbangan Larutan'],
            ['kode' => 'KIM-309', 'nama matakuliah' => 'Kimia Bahan Makanan'],
            ['kode' => 'KIM-306', 'nama matakuliah' => 'Pendidikan Kepramukaan'],
            ['kode' => 'KIM-101', 'nama matakuliah' => 'Kimia Dasar'],
            ['kode' => 'KIM-308', 'nama matakuliah' => 'Asesmen Pembelajaran Kimia'],
            ['kode' => 'KIM-302', 'nama matakuliah' => 'Biokimia II'],
            ['kode' => 'KIM-208', 'nama matakuliah' => 'Praktikum Analisis Instrumen'],
            ['kode' => 'KIM-307', 'nama matakuliah' => 'Reaksi dan Mekanisme Senyawa Organik'],
            ['kode' => 'KIM-203', 'nama matakuliah' => 'Kimia Anorganik II'],
            ['kode' => 'KIM-201', 'nama matakuliah' => 'Kimia Organik I'],
            ['kode' => 'KIM-310', 'nama matakuliah' => 'Praktikum Kimia Bahan Makanan'],
            ['kode' => 'KIM-202', 'nama matakuliah' => 'Disain Praktikum Kimia'],
            ['kode' => 'KIM-105', 'nama matakuliah' => 'Pengetahuan dan Keterampilan Lab'],
            ['kode' => 'KIM-304', 'nama matakuliah' => 'Simulasi Pembelajaran Kimia'],
            ['kode' => 'KIM-315', 'nama matakuliah' => 'Kimia Kelautan'],
            ['kode' => 'KIM-303', 'nama matakuliah' => 'Kimia Sekolah II'],
            ['kode' => 'KIM-207', 'nama matakuliah' => 'Kimia Analisis Instrumen'],
            ['kode' => 'KIM-103', 'nama matakuliah' => 'Fisika Dasar'],
            ['kode' => 'KIM-104', 'nama matakuliah' => 'Matematika Kimia'],
            ['kode' => 'KIM-301', 'nama matakuliah' => 'Metodologi Penelitian'],
            ['kode' => 'KIM-209', 'nama matakuliah' => 'Strategi Pembelajaran Kimia'],
            ['kode' => 'KIM-211', 'nama matakuliah' => 'Telaah Kurikulum dan Materi Kimia Sekolah'],
            ['kode' => 'KIM-407', 'nama matakuliah' => 'Spektroskopi Molekul Organik'],
            ['kode' => 'KIM-305', 'nama matakuliah' => 'Kimia Lingkungan'],
            ['kode' => 'KIM-102', 'nama matakuliah' => 'Praktikum Kimia Dasar'],
            ['kode' => 'KIM-204', 'nama matakuliah' => 'Praktikum Kimia Anorganik II'],
            ['kode' => 'KIM-210', 'nama matakuliah' => 'Media Pembelajaran Kimia'],
            ['kode' => 'KIM-313', 'nama matakuliah' => 'Kimia Polimer'],
            ['kode' => 'KIM-206', 'nama matakuliah' => 'Praktikum Kesetimbangan Larutan'],
            ['kode' => 'EDU-001', 'nama matakuliah' => 'Seminar'],
            ['kode' => 'EDU-002', 'nama matakuliah' => 'Ujian'],

            // PG Paud
            ['kode' => 'PUD-307', 'nama matakuliah' => 'Metodologi Penelitian'],
            ['kode' => 'PUD-302', 'nama matakuliah' => 'Perencanaan Pembelajaran PAUD'],
            ['kode' => 'PUD-201', 'nama matakuliah' => 'Kesehatan dan Gizi AUD'],
            ['kode' => 'PUD-208', 'nama matakuliah' => 'Neuroscience Pembelajaran AUD'],
            ['kode' => 'MFA-102', 'nama matakuliah' => 'Perkembangan Peserta Didik'],
            ['kode' => 'PUD-304', 'nama matakuliah' => 'Literasi Digital'],
            ['kode' => 'PUD-216', 'nama matakuliah' => 'Statistika'],
            ['kode' => 'PUD-209', 'nama matakuliah' => 'Komunikasi Efektif dalam Pendidikan'],
            ['kode' => 'PUD-203', 'nama matakuliah' => 'Pengembangan Kemampuan Sosial Emosional'],
            ['kode' => 'PUD-101', 'nama matakuliah' => 'Perkembangan AUD'],
            ['kode' => 'PUD-306', 'nama matakuliah' => 'Teknik Penulisan Karya Ilmiah'],
            ['kode' => 'PUD-303', 'nama matakuliah' => 'Bermain dan Permainan AUD'],
            ['kode' => 'MKU-106', 'nama matakuliah' => 'Komputer dan Pemrograman (Coding)'],
            ['kode' => 'PUD-202', 'nama matakuliah' => 'Kurikulum PAUD'],
            ['kode' => 'PUD-309', 'nama matakuliah' => 'Pembelajaran Studi Sosial AUD'],
            ['kode' => 'PUD-308', 'nama matakuliah' => 'Pendidikan Seni Musik AUD'],
            ['kode' => 'PUD-205', 'nama matakuliah' => 'Pengembangan Kemampuan Motorik Halus AUD'],
            ['kode' => 'PUD-301', 'nama matakuliah' => 'Evaluasi Pembelajaran PAUD'],
            ['kode' => 'PUD-207', 'nama matakuliah' => 'Pendidikan dalam Keluarga'],
            ['kode' => 'PUD-204', 'nama matakuliah' => 'Pengembangan Kemampuan Motorik Kasar AUD'],
            ['kode' => 'PUD-206', 'nama matakuliah' => 'Pengembangan Kognitif AUD'],
            ['kode' => 'PUD-102', 'nama matakuliah' => 'Konsep Dasar PAUD'],
            ['kode' => 'MKU-101', 'nama matakuliah' => 'Pendidikan Agama'],

            // Bahasa Inggris
            ['kode' => 'ING-342', 'nama matakuliah' => 'Course Design'],
            ['kode' => 'ING-102', 'nama matakuliah' => 'Conversation'],
            ['kode' => 'ING-103', 'nama matakuliah' => 'Intensive Reading'],
            ['kode' => 'ING-214', 'nama matakuliah' => 'Academic Speaking'],
            ['kode' => 'ING-101', 'nama matakuliah' => 'Intensive Listening'],
            ['kode' => 'ING-215', 'nama matakuliah' => 'Extensive Reading'],
            ['kode' => 'ING-341', 'nama matakuliah' => 'Introduction To Educational Research'],
            ['kode' => 'ING-220', 'nama matakuliah' => 'Literature for Educational Purposes'],
            ['kode' => 'ING-105', 'nama matakuliah' => 'Basic English Grammar'],
            ['kode' => 'ING-337', 'nama matakuliah' => 'Media And Materials Development'],
            ['kode' => 'ING-222', 'nama matakuliah' => 'Prose in Language Education'],
            ['kode' => 'ING-223', 'nama matakuliah' => 'Translation'],
            ['kode' => 'ING-340', 'nama matakuliah' => 'Second Language Acquisition'],
            ['kode' => 'ING-335', 'nama matakuliah' => 'Pragmatics'],
            ['kode' => 'ING-343', 'nama matakuliah' => 'English for Journalism'],
            ['kode' => 'ING-221', 'nama matakuliah' => 'Drama in Language Education'],
            ['kode' => 'MKU-300', 'nama matakuliah' => 'Kewirausahaan/Entrepreneurship'],
            ['kode' => 'ING-336', 'nama matakuliah' => 'English For Specific Purposes'],
            ['kode' => 'ING-219', 'nama matakuliah' => 'English Morphology'],
            ['kode' => 'ING-217', 'nama matakuliah' => 'Grammar in Written Discourse'],
            ['kode' => 'ING-213', 'nama matakuliah' => 'Extensive Listening'],
            ['kode' => 'ING-218', 'nama matakuliah' => 'Phonetics And Phonology'],
            ['kode' => 'ING-339', 'nama matakuliah' => 'Lesson Planning'],
            ['kode' => 'ING-216', 'nama matakuliah' => 'Academic Writing'],
            ['kode' => 'ING-104', 'nama matakuliah' => 'Paragraph Writing'],
            ['kode' => 'ING-338', 'nama matakuliah' => 'Statistics For Language Research'],

             // Bahasa Indonesia
             ['kode' => 'IND-102', 'nama matakuliah' => 'Kebudayaan Indonesia'],
             ['kode' => 'IND-436', 'nama matakuliah' => 'Kurikulum Bahasa Indonesia'],
             ['kode' => 'IND-312', 'nama matakuliah' => 'Pembinaan dan Pengembangan Bahasa'],
             ['kode' => 'IND-438', 'nama matakuliah' => 'Penilaian Pembelajaran BI'],
             ['kode' => 'IND-114', 'nama matakuliah' => 'Sejarah Sastra'],
             ['kode' => 'IND-440', 'nama matakuliah' => 'Pengembangan Tes BI'],
             ['kode' => 'IND-310', 'nama matakuliah' => 'Analisis Wacana'],
             ['kode' => 'IND-442', 'nama matakuliah' => 'Interaksi Belajar Kelas Bahasa'],
             ['kode' => 'IND-441', 'nama matakuliah' => 'TIK untuk Guru Bahasa (ICT for LT)'],
             ['kode' => 'IND-437', 'nama matakuliah' => 'Pengembangan Bahan Ajar'],
             ['kode' => 'IND-322', 'nama matakuliah' => 'Sastra Bandingan'],
             ['kode' => 'IND-218', 'nama matakuliah' => 'Apresiasi Prosa Fiksi'],
             ['kode' => 'IND-439', 'nama matakuliah' => 'Pengembangan Rancangan PBI'],
             ['kode' => 'IND-220', 'nama matakuliah' => 'Kritik Sastra'],
             ['kode' => 'IND-313', 'nama matakuliah' => 'Perbandingan Bahasa Nusantara'],
             ['kode' => 'IND-311', 'nama matakuliah' => 'Pragmatik dan Retorika'],
             ['kode' => 'IND-204', 'nama matakuliah' => 'Morfologi'],
             ['kode' => 'IND-124', 'nama matakuliah' => 'Keterampilan Menyimak'],
             ['kode' => 'IND-323', 'nama matakuliah' => 'Pembelajaran Sastra'],
             ['kode' => 'IND-231', 'nama matakuliah' => 'Statistik Pendidikan Bahasa Indonesia'],
             ['kode' => 'IND-101', 'nama matakuliah' => 'Linguistik Umum'],
             ['kode' => 'IND-219', 'nama matakuliah' => 'Apresiasi Drama'],
             ['kode' => 'IND-316', 'nama matakuliah' => 'Ekspresi/Membaca Sastra'],
             ['kode' => 'IND-344', 'nama matakuliah' => 'Penelitian Pendidikan Bahasa dan Sastra'],
             ['kode' => 'IND-207', 'nama matakuliah' => 'Bahasa Daerah'],
             ['kode' => 'IND-343', 'nama matakuliah' => 'Penelitian Bahasa dan Sastra'],
             ['kode' => 'IND-124', 'nama matakuliah' => 'Keterampilan Menyimak'],
             ['kode' => 'IND-230', 'nama matakuliah' => 'Pramuka untuk Guru BI'],
 
             // BK
             ['kode' => 'BKO-139', 'nama matakuliah' => 'Pendidikan Anak Berbakat'],
             ['kode' => 'BKO-137', 'nama matakuliah' => 'Psikologi Dewasa dan Usia Lanjut'],
             ['kode' => 'BKO-328', 'nama matakuliah' => 'Pengembangan Profesi Konselor'],
             ['kode' => 'BKO-101', 'nama matakuliah' => 'Wawasan Dasar BK'],
             ['kode' => 'BKO-208', 'nama matakuliah' => 'Bimbingan dan Konseling Karir'],
             ['kode' => 'BKO-240', 'nama matakuliah' => 'Statistik'],
             ['kode' => 'BKO-311', 'nama matakuliah' => 'Bimbingan dan Konseling Klasikal'],
             ['kode' => 'BKO-332', 'nama matakuliah' => 'Metode Penelitian Pendidikan dan BK'],
             ['kode' => 'MKU-100', 'nama matakuliah' => 'Pendidikan Agama'],
             ['kode' => 'BKO-225', 'nama matakuliah' => 'Teknik Laboratorium'],
             ['kode' => 'BKO-102', 'nama matakuliah' => 'Komunikasi Antar Pribadi'],
             ['kode' => 'BKO-307', 'nama matakuliah' => 'Bimbingan dan Konseling Belajar'],
             ['kode' => 'BKO-205', 'nama matakuliah' => 'Pendekatan Konseling'],
             ['kode' => 'BKO-310', 'nama matakuliah' => 'Diagnostik Kesulitan Belajar, Remedial dan Pengayaan'],
             ['kode' => 'BKO-233', 'nama matakuliah' => 'Psikologi Kepribadian'],
             ['kode' => 'BKO-313', 'nama matakuliah' => 'Psikologi Konseling'],
             ['kode' => 'BKO-214', 'nama matakuliah' => 'Asesmen Individu Teknik Non Tes'],
             ['kode' => 'BKO-134', 'nama matakuliah' => 'Psikologi Umum'],
             ['kode' => 'BKO-316', 'nama matakuliah' => 'Konseling Kesehatan Reproduksi'],
 
             // Matematika
             ['kode' => 'PMAT-103', 'nama matakuliah' => 'Trigonometri'],
             ['kode' => 'MKU-300', 'nama matakuliah' => 'Kewirausahaan'],
             ['kode' => 'MKU-104', 'nama matakuliah' => 'Pendidikan Kewarganegaraan'],
             ['kode' => 'PMAT-111', 'nama matakuliah' => 'Statistik Lanjut'],
             ['kode' => 'PMAT-208', 'nama matakuliah' => 'Kapita Selekta Matematika Jenjang Pendidikan Menengah'],
             ['kode' => 'PMAT-115', 'nama matakuliah' => 'Analisis Real'],
             ['kode' => 'PMAT-304', 'nama matakuliah' => 'Seminar'],
             ['kode' => 'PMAT-110', 'nama matakuliah' => 'Kalkulus Integral'],
             ['kode' => 'PMAT-303', 'nama matakuliah' => 'Penelitian Pendidikan Matematika'],
             ['kode' => 'PMAT-104', 'nama matakuliah' => 'Aljabar Rendah'],
             ['kode' => 'PMAT-202', 'nama matakuliah' => 'Media Pembelajaran Matematika'],
             ['kode' => 'PMAT-203', 'nama matakuliah' => 'Pembelajaran Matematika Inovatif'],
             ['kode' => 'PMAT-116', 'nama matakuliah' => 'Aljabar Abstrak'],
             ['kode' => 'PMAT-118', 'nama matakuliah' => 'Persamaan Diferensial'],
             ['kode' => 'PMAT-119', 'nama matakuliah' => 'Statistik Non Parametrik'],
             ['kode' => 'PMAT-313', 'nama matakuliah' => 'Pengembangan Media Manipulatif'],
             ['kode' => 'PMAT-117', 'nama matakuliah' => 'Sistem Geometri'],
             ['kode' => 'MFA-105', 'nama matakuliah' => 'Pengelolaan Pendidikan'],
             ['kode' => 'PMAT-109', 'nama matakuliah' => 'Matematika Diskrit'],
             ['kode' => 'PMAT-102', 'nama matakuliah' => 'Teori Bilangan'],
             ['kode' => 'PMAT-110', 'nama matakuliah' => 'Pratikum Kalkulus Integral'],
             ['kode' => 'PMAT-204', 'nama matakuliah' => 'Evaluasi Pembelajaran Matematika'],
             ['kode' => 'PMAT-202', 'nama matakuliah' => 'Pratikum Media Pembelajaran Matematika'],
             ['kode' => 'PMAT-204', 'nama matakuliah' => 'Pratikum Evaluasi Pembelajaran Matematika'],
             ['kode' => 'PMAT-101', 'nama matakuliah' => 'Matematika Dasar'],
 
             // Fisika
             ['kode' => '0', 'nama matakuliah' => 'Kurikulum dan Pembelajaran'],
             ['kode' => '0', 'nama matakuliah' => 'Listrik Magnet'],
             ['kode' => '0', 'nama matakuliah' => 'Diferensiasi dan Integral Untuk Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Mekanika'],
             ['kode' => '0', 'nama matakuliah' => 'Strategi Pembelajaran Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Pengembangan Bahan Ajar'],
             ['kode' => '0', 'nama matakuliah' => 'Mekanika Klasik'],
             ['kode' => '0', 'nama matakuliah' => 'Pengembangan Eksperimen Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Termodinamika'],
             ['kode' => '0', 'nama matakuliah' => 'Perkembangan Peserta Didik'],
             ['kode' => '0', 'nama matakuliah' => 'Gelombang'],
             ['kode' => '0', 'nama matakuliah' => 'Media Pembelajaran Berbasis Android'],
             ['kode' => '0', 'nama matakuliah' => 'Pembelajaran Fisika Bauran'],
             ['kode' => '0', 'nama matakuliah' => 'Hidrodinamika'],
             ['kode' => '0', 'nama matakuliah' => 'Bahasa Inggris untuk Guru Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Praktikum Gelombang'],
             ['kode' => '0', 'nama matakuliah' => 'Inovasi Pembelajaran Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Elektronika'],
             ['kode' => '0', 'nama matakuliah' => 'Manajemen Lembaga Pendidikan'],
             ['kode' => '0', 'nama matakuliah' => 'Perencanaan Pembelajaran Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Studi Kasus Pendidikan Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Aplikasi Teknologi Pada Pembelajaran Fisika'],
             ['kode' => '0', 'nama matakuliah' => 'Kewirausahaan'],
             ['kode' => '0', 'nama matakuliah' => 'Pengelolaan Pendidikan'],
             ['kode' => '0', 'nama matakuliah' => 'Praktikum Elektronika'],

              //PGSD
            ['kode' => 'GSD-101', 'nama matakuliah' => 'Kajian Kebahasaan'],
            ['kode' => 'MKU-103', 'nama matakuliah' => 'Bahasa Indonesia'],
            ['kode' => 'GSD-207', 'nama matakuliah' => 'Pendidikan Seni Rupa dan Prakarya di SD'],
            ['kode' => 'GSD-2043', 'nama matakuliah' => 'Konsep Dasar IPA Biologi'],
            ['kode' => 'GSD-201', 'nama matakuliah' => 'Konsep Dasar PKn SD'],
            ['kode' => 'GSD-206', 'nama matakuliah' => 'Pendidikan Nilai dan Moral'],
            ['kode' => 'GSD-202', 'nama matakuliah' => 'Keterampilan Berbahasa Indonesia'],
            ['kode' => 'GSD-209', 'nama matakuliah' => 'Pendidikan Seni Tari di SD'],
            ['kode' => 'GSD-205', 'nama matakuliah' => 'Pendidikan IPS SD'],
            ['kode' => 'GSD-203', 'nama matakuliah' => 'Geometri dan Pengukuran'],
            ['kode' => 'GSD-208', 'nama matakuliah' => 'PJOK SD'],
            ['kode' => 'GSD-305', 'nama matakuliah' => 'Pengembangan Pembelajaran PKn SD'],
            ['kode' => 'GSD-307', 'nama matakuliah' => 'Manajemen Pendidikan di SD'],
            ['kode' => 'GSD-312', 'nama matakuliah' => 'Pengembangan Pembelajaran Matematika SD'],
            ['kode' => 'GSD-304', 'nama matakuliah' => 'Pengembangan Pembelajaran IPS SD'],
            ['kode' => 'GSD-306', 'nama matakuliah' => 'Pengembangan Kreativitas Seni Budaya di SD'],
            ['kode' => 'GSD-301', 'nama matakuliah' => 'Pengembangan Pembelajaran Bahasa dan Sastra Indonesia SD'],
            ['kode' => 'GSD-303', 'nama matakuliah' => 'Pengembangan Pembelajaran IPA SD'],
            ['kode' => 'GSD-401', 'nama matakuliah' => 'Pendidikan Keaksaraan'],
            ['kode' => 'GSD-403', 'nama matakuliah' => 'Pembelajaran Tematik Terpadu'],
            ['kode' => 'GSD-404', 'nama matakuliah' => 'Penelitian Tindakan Kelas dan Lesson Study'],
            ['kode' => 'GSD-405', 'nama matakuliah' => 'Evaluasi Pembelajaran'],
            ['kode' => 'GSD-406', 'nama matakuliah' => 'Media Pembelajaran TIK'],
        ];

        // Insert data into the database
        foreach ($matkul as $mk) {
            DB::table('matkul')->insert([
                'kode' => $mk['kode'],
                'nama matakuliah' => $mk['nama matakuliah'],
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
